version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: frontend-bumps
  ignore:
  - dependency-name: np
  automerged_updates:
    - match:
        dependency_type: "all"
